import { twMerge } from 'tailwind-merge';

const sizes = {
  xs: [
    'w-[30px]',
    'h-4',
    'before:h-3',
    'before:w-3',
    'before:top-0.5',
    'before:left-0.5',
    'before:shadow-[0_0.5px_1px_0px_rgba(0,0,0,0.25)]',
    'hover:before:w-4',
    'checked:before:left-4',
    'checked:hover:before:left-3',
    'disabled:hover:before:w-3',
    'disabled:hover:before:left-0.5',
    'disabled:checked:hover:before:left-4',
    'focus-visible:ring-offset-1',
  ],
  sm: [
    'w-[45px]',
    'h-6',
    'before:h-[18px]',
    'before:w-[18px]',
    'before:top-[3px]',
    'before:left-[3px]',
    'before:shadow-[0_0.75px_1.5px_0px_rgba(0,0,0,0.25)]',
    'hover:before:w-6',
    'checked:before:left-6',
    'checked:hover:before:left-[18px]',
    'disabled:hover:before:w-[18px]',
    'disabled:hover:before:left-[3px]',
    'disabled:checked:hover:before:left-6',
    'focus-visible:ring-offset-1',
  ],
  md: [
    'w-[60px]',
    'h-8',
    'before:h-6',
    'before:w-6',
    'before:top-1',
    'before:left-1',
    'before:shadow-[0_1px_2px_0px_rgba(0,0,0,0.25)]',
    'hover:before:w-8',
    'checked:before:left-8',
    'checked:hover:before:left-6',
    'disabled:hover:before:w-6',
    'disabled:hover:before:left-1',
    'disabled:checked:hover:before:left-8',
    'focus-visible:ring-offset-2',
  ],
  lg: [
    'w-[75px]',
    'h-10',
    'before:h-[30px]',
    'before:w-[30px]',
    'before:top-[5px]',
    'before:left-[5px]',
    'before:shadow-[0_1.25px_2.5px_0px_rgba(0,0,0,0.25)]',
    'hover:before:w-10',
    'checked:before:left-10',
    'checked:hover:before:left-[30px]',
    'disabled:hover:before:w-[30px]',
    'disabled:hover:before:left-[5px]',
    'disabled:checked:hover:before:left-10',
    'focus-visible:ring-offset-2',
  ],
  xl: [
    'w-[90px]',
    'h-12',
    'before:h-9',
    'before:w-9',
    'before:top-1.5',
    'before:left-1.5',
    'before:shadow-[0_1.5px_3px_0px_rgba(0,0,0,0.25)]',
    'hover:before:w-12',
    'checked:before:left-12',
    'checked:hover:before:left-9',
    'disabled:hover:before:w-9',
    'disabled:hover:before:left-1.5',
    'disabled:checked:hover:before:left-12',
    'focus-visible:ring-offset-2',
  ],
};

const variants = {
  primary: ['checked:bg-primary-70', 'checked:dark:bg-primary-60'],
  secondary: ['checked:bg-secondary-70', 'checked:dark:bg-secondary-60'],
  aqua: ['checked:bg-aqua-60', 'checked:dark:bg-aqua-50'],
  green: ['checked:bg-green-60', 'checked:dark:bg-green-60'],
  yellow: ['checked:bg-yellow-60', 'checked:dark:bg-yellow-50'],
  orange: ['checked:bg-orange-60', 'checked:dark:bg-orange-60'],
  red: ['checked:bg-red-50', 'checked:dark:bg-red-50'],
  pink: ['checked:bg-pink-60', 'checked:dark:bg-pink-40'],
  purple: ['checked:bg-purple-60', 'checked:dark:bg-purple-40'],
  blue: ['checked:bg-blue-60', 'checked:dark:bg-blue-50'],
};

export const getSwitchClassName = ({
  className,
  size = 'xs',
  variant = 'primary',
} = {}) =>
  twMerge(
    [
      'appearance-none',
      'bg-neutral-20',
      'outline-none',
      'relative',
      'rounded-full',
      'cursor-pointer',
      'before:absolute',
      'before:bg-white',
      'before:duration-300',
      'before:ease-in-out',
      'before:rounded-full',
      'before:transition-left',
      'disabled:opacity-30',
      'disabled:cursor-auto',
      'disabled:before:shadow-none',
      'focus-visible:ring-2',
      'focus-visible:ring-offset-white',
      'focus-visible:ring-primary-80',
      'dark:bg-neutral-60',
      'dark:before:bg-neutral-20',
      'dark:checked:before:bg-white',
      'dark:focus-visible:ring-offset-black',
      'dark:focus-visible:ring-primary-60',
    ],
    size && sizes[size],
    variant && variants[variant],
    className,
  );

export default getSwitchClassName;
